#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := sound_project
EXTRA_COMPONENT_DIRS += $(ADF_PATH)/components  
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/sound_project/components/esp-dsp/modules

include $(IDF_PATH)/make/project.mk

